name: Build Site

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/dependabot.yml"
    branches-ignore:
      - "deploy"
  pull_request:
  workflow_dispatch:
  
jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        npm install
    - name: Build Typescript
      run: |
        npm run build-ts
    - name: Upload Built Typescript
      uses: actions/upload-artifact@v3.1.1
      with:
        name: index.js
        path: dist/index.js
  scss:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        npm install
    - name: Build SCSS
      run: |
        npm run scss-update
    - name: Upload Built SCSS
      uses: actions/upload-artifact@v3.1.1
      with:
        name: style.css
        path: dist/style.css
  clear:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [typescript, scss]
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      with:
        path: deploy
    - name: Clear
      run: |
        rm -rf *
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: .
         publish_branch: deploy
         allow_empty_commit: true
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [clear]
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      
    - name: Download JS
      uses: actions/download-artifact@v3
      with:
        name: index.js
        path: dist/
    - name: Download CSS
      uses: actions/download-artifact@v3
      with:
        name: style.css
        path: dist/
        
    - name: Copy Public
      run: |
        npm run copy-public
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./dist
         publish_branch: deploy
         allow_empty_commit: true
